replicaCount: 1

image:
  repository: 533260833584.dkr.ecr.us-east-1.amazonaws.com/acceleraterapp
  tag: alpha-latest   # Update with your actual Next.js image tag
  pullPolicy: IfNotPresent

containerPort: 3000

env:
  - name: PORT
    value: "3000"

envFrom:
  - secretRef:
      name: rds-secrets   # The Kubernetes Secret synced from rds-db-secret-provider

service:
  type: ClusterIP
  port: 3000

serviceAccount:
  create: false
  name: ""

ingress:
  enabled: true
  className: nginx
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: gitaction.dev.stackgenie.io   # Replace with your real domain
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: nextjs-app
              port:
                number: 3000
  tls: []

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80
