replicaCount: 1

app:
  image:
    repository: 533260833584.dkr.ecr.us-east-1.amazonaws.com/acceleraterapp
    tag: alpha-latest   # update with your actual Next.js image tag
    pullPolicy: IfNotPresent
  containerPort: 3000
  envFrom:
    - secretProviderClass:
        name: rds-db-secret-provider   # Use the SecretProviderClass here
  service:
    type: ClusterIP
    port: 3000

serviceAccount:
  create: false
  name: ""

ingress:
  enabled: true
  className: nginx
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: gitaction.dev.stackgenie.io   # replace with your real domain
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: nextjs-app
              port:
                number: 3000
  tls: []
